version: "3.3"

services:
  database_somosUm:
    image: postgres
    container_name: database_somosUm
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=777777
      - POSTGRES_DB=somosuum
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
